# Generated by Django 5.1.7 on 2025-03-26 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compunotesapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='files', to='compunotesapi.tag'),
        ),
    ]
