# Generated by Django 5.1.7 on 2025-04-30 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compunotesapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(db_collation='utf8mb4_bin', max_length=255),
        ),
    ]
