# Generated by Django 5.1.7 on 2025-03-26 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compunotesapi', '0002_alter_file_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='title',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
