# Generated by Django 5.1.7 on 2025-03-27 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compunotesapi', '0003_alter_file_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='path',
            field=models.FilePathField(max_length=255, path='/home/compunotes/files', unique=True),
        ),
    ]
