# Generated by Django 5.1.7 on 2025-03-27 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compunotesapi', '0004_alter_file_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='path',
            field=models.FilePathField(max_length=255, path='/home/compunotes/files', recursive=True, unique=True),
        ),
    ]
